Fix running crash Fix createdmg script error

diff --git a/createdmg b/createdmg
--- a/createdmg
+++ b/createdmg
@@ -1,21 +1,39 @@
 #!/bin/bash
 
 #TARGET=Debug
-TARGET=Release
+PROJECT="machoview.xcodeproj"
+CONFIGURATION="Release"
+SCHEME="MachOView"
 
-# Build disassembler
-cd otool_disasm
-/usr/bin/xcodebuild -configuration $TARGET
-cp -f build/$TARGET/libdisasm.a ..
-cd ..
+BUILD_DIR=$(PWD)/build
 
+if [[ -d $BUILD_DIR ]]; then
+    rm -rf $BUILD_DIR
+    echo "clean build dir ..."
+fi
+
+# clean
+xcodebuild clean -project $PROJECT
 # Build MachOView
-/usr/bin/xcodebuild -configuration $TARGET
+xcodebuild build \
+        -project $PROJECT \
+        -scheme $SCHEME \
+        -configuration $CONFIGURATION \
+        SYMROOT=$(PWD)/build
 
+if [[ $? != 0 ]]; then
+    echo "build failure: exit code $?"
+    exit 0
+fi
 # Create DMG Installer
-buildPlist="build/"$TARGET"/MachOView.app/Contents/Info.plist"
+cp -f ./Applications $BUILD_DIR/$CONFIGURATION/Applications
+buildPlist=$BUILD_DIR/$CONFIGURATION/$SCHEME.app/Contents/Info.plist
 CFBuildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBuildNumber" $buildPlist)
 CFBundleShortVersionString=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" $buildPlist)
-cp -f README "build/"$TARGET
+cp -f README $BUILD_DIR/$CONFIGURATION
 
-hdiutil create -fs HFS+ -volname "MachOView" -srcfolder "build/"$TARGET "MachOView-"$CFBundleShortVersionString.$CFBuildNumber".dmg"
+hdiutil create \
+    -fs HFS+ \
+    -volname "$SCHEME" \
+    -srcfolder $BUILD_DIR/$CONFIGURATION \
+    "MachOView-"$CFBundleShortVersionString.$CFBuildNumber".dmg"
